language: node_js
node_js:
- node
- '6'
cache: yarn
after_success: npm run coveralls
deploy:
  provider: npm
  email: gordon@gordonburgett.net
  api_key:
    secure: LIvzUcnw4o9hpLoLJluwzWteDbe3R1FhAsAoKZq/c8WUrdsj1ElcE5bUQQTSBV0MCrQK0HFZsFeDEZHyueumE7bbJsHIPb5/1P0EZVH8Ua+xSpnaVp86tnzz0euyLlz3//SR82TOPHuWKImfIITMs/bKghxBkVNuIRWEJ0UAZqCiYn81qpi/bSBiv48KboSSnyzZbxLiEDxjile46jsAmQVXu5VkYZ3cPHHzLsv0CngypH/6KASPSamDyohtzAe2lQ5lynUG/oW/6DouRFVhIjCEUrYAWT9OwVgGQkgemR9qqz5y/RSN7Q7mAf06f4zGgw9VUUM3jIJp1uGqD2TMfexlDBRUHftOHcm/bkVoeCgYupXrId+wEgr/HUUady2/BXI2bN3wy8WZWPtURrEuEws8AmhZAxowmaGdadPA5vCwSTnURJmx/wvwu4jBZCZRkw9EJnp0raHc+8UCNyRpWmnTHtc6NGgdqZlNzg/JzN9lf4XoKFwvRlGjSJ/I76m0kUnqVXA71H1R8oCU/dIgmQZO+fU/0Ba5vpUcP5UZISrAfr3iD3xXoiuN5cAnJwWTDU4LEH8pHdWraxlBmDFCcyCxEm9GlyJEvkYmT3pCdzii4WmDJHr73NbqaUdmrN63MhxdoIfTOwQvROH+BQuqq/RJJJfDyjAdZw38Ytajtcw=
  on:
    branch: release
    repo: gburgett/tapconvey
